/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_say = 1,
  anon_sym_narrate = 2,
  anon_sym_jump = 3,
  anon_sym_label = 4,
  sym_end = 5,
  anon_sym_bg = 6,
  anon_sym_char = 7,
  anon_sym_menu = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_DASH_GT = 11,
  sym_identifier = 12,
  sym_filename = 13,
  sym_string = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym_statement = 17,
  sym_say = 18,
  sym_narrate = 19,
  sym_jump = 20,
  sym_label = 21,
  sym_bg = 22,
  sym_char = 23,
  sym_menu = 24,
  sym_choice = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_menu_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_say] = "say",
  [anon_sym_narrate] = "narrate",
  [anon_sym_jump] = "jump",
  [anon_sym_label] = "label",
  [sym_end] = "end",
  [anon_sym_bg] = "bg",
  [anon_sym_char] = "char",
  [anon_sym_menu] = "menu",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DASH_GT] = "->",
  [sym_identifier] = "identifier",
  [sym_filename] = "filename",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_say] = "say",
  [sym_narrate] = "narrate",
  [sym_jump] = "jump",
  [sym_label] = "label",
  [sym_bg] = "bg",
  [sym_char] = "char",
  [sym_menu] = "menu",
  [sym_choice] = "choice",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_menu_repeat1] = "menu_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_say] = anon_sym_say,
  [anon_sym_narrate] = anon_sym_narrate,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_label] = anon_sym_label,
  [sym_end] = sym_end,
  [anon_sym_bg] = anon_sym_bg,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_menu] = anon_sym_menu,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_identifier] = sym_identifier,
  [sym_filename] = sym_filename,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_say] = sym_say,
  [sym_narrate] = sym_narrate,
  [sym_jump] = sym_jump,
  [sym_label] = sym_label,
  [sym_bg] = sym_bg,
  [sym_char] = sym_char,
  [sym_menu] = sym_menu,
  [sym_choice] = sym_choice,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_menu_repeat1] = aux_sym_menu_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_say] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_narrate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_label] = {
    .visible = true,
    .named = false,
  },
  [sym_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_bg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_menu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_say] = {
    .visible = true,
    .named = true,
  },
  [sym_narrate] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_bg] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_menu] = {
    .visible = true,
    .named = true,
  },
  [sym_choice] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_menu_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_file = 1,
  field_name = 2,
  field_pose = 3,
  field_speaker = 4,
  field_target = 5,
  field_text = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_file] = "file",
  [field_name] = "name",
  [field_pose] = "pose",
  [field_speaker] = "speaker",
  [field_target] = "target",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_text, 1},
  [1] =
    {field_target, 1},
  [2] =
    {field_name, 1},
  [3] =
    {field_file, 1},
  [4] =
    {field_speaker, 1},
    {field_text, 2},
  [6] =
    {field_name, 1},
    {field_pose, 2},
  [8] =
    {field_target, 2},
    {field_text, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '"', 1,
        '#', 45,
        '-', 4,
        'b', 15,
        'c', 16,
        'e', 19,
        'j', 26,
        'l', 5,
        'm', 14,
        'n', 6,
        's', 7,
        '{', 39,
        '}', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(44);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'y') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_say);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_narrate);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_jump);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_label);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_bg);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_menu);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_say] = ACTIONS(1),
    [anon_sym_narrate] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_label] = ACTIONS(1),
    [sym_end] = ACTIONS(1),
    [anon_sym_bg] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_menu] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym_statement] = STATE(2),
    [sym_say] = STATE(4),
    [sym_narrate] = STATE(4),
    [sym_jump] = STATE(4),
    [sym_label] = STATE(4),
    [sym_bg] = STATE(4),
    [sym_char] = STATE(4),
    [sym_menu] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_say] = ACTIONS(7),
    [anon_sym_narrate] = ACTIONS(9),
    [anon_sym_jump] = ACTIONS(11),
    [anon_sym_label] = ACTIONS(13),
    [sym_end] = ACTIONS(15),
    [anon_sym_bg] = ACTIONS(17),
    [anon_sym_char] = ACTIONS(19),
    [anon_sym_menu] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_statement] = STATE(3),
    [sym_say] = STATE(4),
    [sym_narrate] = STATE(4),
    [sym_jump] = STATE(4),
    [sym_label] = STATE(4),
    [sym_bg] = STATE(4),
    [sym_char] = STATE(4),
    [sym_menu] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_say] = ACTIONS(7),
    [anon_sym_narrate] = ACTIONS(9),
    [anon_sym_jump] = ACTIONS(11),
    [anon_sym_label] = ACTIONS(13),
    [sym_end] = ACTIONS(15),
    [anon_sym_bg] = ACTIONS(17),
    [anon_sym_char] = ACTIONS(19),
    [anon_sym_menu] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(3),
    [sym_say] = STATE(4),
    [sym_narrate] = STATE(4),
    [sym_jump] = STATE(4),
    [sym_label] = STATE(4),
    [sym_bg] = STATE(4),
    [sym_char] = STATE(4),
    [sym_menu] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_say] = ACTIONS(27),
    [anon_sym_narrate] = ACTIONS(30),
    [anon_sym_jump] = ACTIONS(33),
    [anon_sym_label] = ACTIONS(36),
    [sym_end] = ACTIONS(39),
    [anon_sym_bg] = ACTIONS(42),
    [anon_sym_char] = ACTIONS(45),
    [anon_sym_menu] = ACTIONS(48),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [15] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [30] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [45] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [60] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [75] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [90] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 9,
      ts_builtin_sym_end,
      anon_sym_say,
      anon_sym_narrate,
      anon_sym_jump,
      anon_sym_label,
      sym_end,
      anon_sym_bg,
      anon_sym_char,
      anon_sym_menu,
  [120] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(69), 1,
      sym_string,
    STATE(13), 2,
      sym_choice,
      aux_sym_menu_repeat1,
  [134] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 1,
      sym_string,
    STATE(13), 2,
      sym_choice,
      aux_sym_menu_repeat1,
  [148] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_string,
    STATE(12), 2,
      sym_choice,
      aux_sym_menu_repeat1,
  [159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_RBRACE,
      sym_string,
  [167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
  [174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_identifier,
  [181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym_string,
  [188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_string,
  [195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_identifier,
  [202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
  [209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
  [216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_identifier,
  [223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_string,
  [230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_filename,
  [237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DASH_GT,
  [244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 15,
  [SMALL_STATE(6)] = 30,
  [SMALL_STATE(7)] = 45,
  [SMALL_STATE(8)] = 60,
  [SMALL_STATE(9)] = 75,
  [SMALL_STATE(10)] = 90,
  [SMALL_STATE(11)] = 105,
  [SMALL_STATE(12)] = 120,
  [SMALL_STATE(13)] = 134,
  [SMALL_STATE(14)] = 148,
  [SMALL_STATE(15)] = 159,
  [SMALL_STATE(16)] = 167,
  [SMALL_STATE(17)] = 174,
  [SMALL_STATE(18)] = 181,
  [SMALL_STATE(19)] = 188,
  [SMALL_STATE(20)] = 195,
  [SMALL_STATE(21)] = 202,
  [SMALL_STATE(22)] = 209,
  [SMALL_STATE(23)] = 216,
  [SMALL_STATE(24)] = 223,
  [SMALL_STATE(25)] = 230,
  [SMALL_STATE(26)] = 237,
  [SMALL_STATE(27)] = 244,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_narrate, 2, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bg, 2, 0, 4),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3, 0, 6),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2, 0, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say, 3, 0, 5),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 3, 0, 7),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [90] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vn_script(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vn_script",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
